### ISSUE TITLE
Improve README.md docs regarding how to configure Ark for DO spaces

### ISSUE THREAD

**Issue by rosskukulinski** [StackPointCloud/ark-plugin-digitalocean#5]
While this plugin adds block-storage support for DO, it also includes information on how to use DO spaces for storing backups.

It would be great if there was a dedicated section on configuring Ark to use DigitalOcean spaces.  The README does cover this (`Update the examples/10-ark-config.yaml`), but it's mixed in with a lot of other content.

I also incorrectly configured the ark-config.yaml by replacing <region> with `space.region`.  Walking users through this setup process will streamline their experience getting up and running.

**Comment by rosskukulinski** [comment]
Refs https://github.com/heptio/ark/pull/783

**Comment by edevenport** [comment]
@rosskukulinski I have a pending PR with an updated README. I retained the existing steps as a quickstart since it loads the predefined example files (and makes testing very easy with copy/paste).

I then added separate sections describing the block store and object store configurations. A user can review the separate sections for more details on each component.

Thoughts?
